### ISSUE TITLE
8.2001.0 package is not signed

### ISSUE THREAD

**Issue by dkgramming** [rsyslog/rsyslog#4122]
Hi there,

It appears that the most recent release, rsyslog-8.2001.0-1.el7  (uploaded today), from http://rpms.adiscon.com/v8-stable/epel-7/x86_64 is not signed with the appropriate GPG key.

### Expected behavior

```
yum -d0 -e0 -y install rsyslog-8.2001.0-1.el7
```

### Actual behavior

```
yum -d0 -e0 -y install rsyslog-8.2001.0-1.el7
Package rsyslog-kafka-8.2001.0-1.el7.x86_64.rpm is not signed
```

**Comment by alorbach** [comment]
I did a verify with rpm a few moments ago, and it appears to be valid: 

**rpm -K rsyslog-kafka-8.2001.0-1.el7.x86_64.rpm
rsyslog-kafka-8.2001.0-1.el7.x86_64.rpm: sha1 md5 OK**

Can you verify if our public GPG Key (http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon) is imported on your system?

**Comment by alorbach** [comment]
The issue has been fixed, there was a problem with the sign process since caused by recent changes in the build process. 

You will need to clean downloaded data first, like with: 

**yum clean all**

@dkgramming Can you confirm that the issue is fixed for you?

**Comment by olgafandeliuk** [comment]
Works well now. Thanks for quick fix=)

**Comment by dkgramming** [comment]
@alorbach Confirmed -- thank you!

**Comment by scottstevinson** [comment]
Looks like this is still an issue with the latest release:

`
wget http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/rsyslog-8.2001.0-1.el7.x86_64.rpm
wget http://rpms.adiscon.com/v8-stable/epel-7/x86_64/RPMS/rsyslog-8.2001.0-2.el7.x86_64.rpm

rpm -qpi rsyslog-8.2001.0-1.el7.x86_64.rpm | grep Signature
warning: rsyslog-8.2001.0-1.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID e00b8985: NOKEY
Signature   : RSA/SHA256, Wed 15 Jan 2020 04:00:24 AM EST, Key ID e0f233b3e00b8985

rpm -qpi rsyslog-8.2001.0-2.el7.x86_64.rpm | grep Signature
Signature   : (none)
`
