### ISSUE TITLE
A lot of CLOSE_WAIT sockets during connection to AWS Elasticsearch in 8.2001 version and latest of rsyslog

### ISSUE THREAD

**Issue by gartemiev** [rsyslog/rsyslog#4468]
Recently We switched to Ubuntu 20.04 and installed rsyslog 8.2001. 
And We have noticed a lot of CLOSE_WAIT connections to AWS managed Elasticsearch.

Our configuration of omelasticsearch is the next: 
```
input(type="imudp" port="41001" ruleset="remote41001")

template(name="json-template" type="list") {
        constant(value="{")
        constant(value="\"@timestamp\":\"")     property(name="timereported" dateFormat="rfc3339")
        constant(value="\",\"@version\":\"1")
        constant(value="\",\"message\":\"")     property(name="msg" format="json")
        constant(value="\",\"sysloghost\":\"")  property(name="hostname")
        constant(value="\",\"severity\":\"")    property(name="syslogseverity-text")
        constant(value="\",\"facility\":\"")    property(name="syslogfacility-text")
        constant(value="\",\"programname\":\"") property(name="programname")
        constant(value="\",\"procid\":\"")      property(name="procid")
        constant(value="\"}\n")
}
template(name="bulkid-template" type="list") {
    property(name="$!es_record_id")
}
template(name="pt-dev-index" type="string" string="pt-dev-%$YEAR%.%$MONTH%.%$DAY%")
ruleset(name="remote41001"){
    set $!es_record_id = $uuid;
    action( type="omelasticsearch"
        bulkmode="on"
        bulkid="bulkid-template"
        dynbulkid="on"
        template="json-template"
        searchIndex="pt-dev-index"
        dynSearchIndex="on"
        errorfile="/var/log/omelasticsearch-dev-41001.log"
        server="https:/xxxx"
        serverport="443"
        queue.type="linkedlist"
        queue.size="5000"
        writeoperation="create"
        retryfailures="on"
        rebindinterval="1000"
        usehttps="on"
        queue.dequeuebatchsize="300"
        action.resumeretrycount="-1"
    )        
}
```
We have 41 services with similar configuration which push logs to AWS managed Elasticsearch.
We also tried to setup the latest version of rsyslog and observed the same behaviour. 
For temporary fixing - We set up rebindinterval parameter to 1000 - it has helped to resolve situation for almost 2 weeks but then it happened again. 

In logs We have noticed that the main queue because of this is growing and overflown: 
```
Thu Nov 19 23:02:12 2020: main Q: origin=core.queue size=168 enqueued=41576109 full=585 discarded.full=518 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:07:12 2020: main Q: origin=core.queue size=26886 enqueued=41609192 full=585 discarded.full=518 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:12:12 2020: main Q: origin=core.queue size=58951 enqueued=41641769 full=585 discarded.full=518 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:17:12 2020: main Q: origin=core.queue size=95038 enqueued=41678112 full=585 discarded.full=518 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:22:12 2020: main Q: origin=core.queue size=100000 enqueued=41683467 full=723 discarded.full=654 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:27:13 2020: main Q: origin=core.queue size=100000 enqueued=41683894 full=894 discarded.full=824 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:32:13 2020: main Q: origin=core.queue size=100000 enqueued=41684299 full=1044 discarded.full=973 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:37:13 2020: main Q: origin=core.queue size=100000 enqueued=41684960 full=1195 discarded.full=1122 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:42:13 2020: main Q: origin=core.queue size=100000 enqueued=41685389 full=1369 discarded.full=1295 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:47:13 2020: main Q: origin=core.queue size=100000 enqueued=41685794 full=1519 discarded.full=1444 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:52:13 2020: main Q: origin=core.queue size=100000 enqueued=41686722 full=1681 discarded.full=1604 discarded.nf=0 maxqsize=100000 
Thu Nov 19 23:57:13 2020: main Q: origin=core.queue size=100000 enqueued=41687403 full=1852 discarded.full=1773 discarded.nf=0 maxqsize=100000 
```
As a result it caused log lost and high load on our VMs where rsyslog is installed. 

Any clue how to fix this issue?

**Comment by gartemiev** [comment]
@rgerhards could you please help with this?

**Comment by davidelang** [comment]
is there anything being logged on the ES side? (is it closing connections for 
some reason)

what is the volume of logs being delivered? sockets remain in close_wait for a 
few minutes, so if your 1000 rebind is only a few seconds worth of logs, you 
would have a bunch of sockets in that state from that.

you can set rebindinterval even larger, you really only want to rebind if you 
are loadbalancing, otherise there's no reason to.

David Lang

  On Fri, 20 Nov 2020, 
George Artemiev wrote:

> Date: Fri, 20 Nov 2020 01:21:23 -0800
> From: George Artemiev <notifications@github.com>
> Reply-To: rsyslog/rsyslog
>     <reply@reply.github.com>
> To: rsyslog/rsyslog <rsyslog@noreply.github.com>
> Cc: Subscribed <subscribed@noreply.github.com>
> Subject: [rsyslog/rsyslog] A lot of CLOSE_WAIT sockets during connection to
>     AWS Elasticsearch in 8.2001 version and latest of rsyslog (#4468)
> 
> Recently We switched to Ubuntu 20.04 and installed rsyslog 8.2001.
> And We have noticed a lot of CLOSE_WAIT connections to AWS managed Elasticsearch.
>
> Our configuration of omelasticsearch is the next:
> ```
> ruleset(name="remote41001"){
>    set $!es_record_id = $uuid;
>    action( type="omelasticsearch"
>        bulkmode="on"
>        bulkid="bulkid-template"
>        dynbulkid="on"
>        template="json-template"
>        searchIndex="pt-dev-index"
>        dynSearchIndex="on"
>        errorfile="/var/log/omelasticsearch-dev-41001.log"
>        server="https:/xxxx"
>        serverport="443"
>        queue.type="linkedlist"
>        queue.size="5000"
>        writeoperation="create"
>        retryfailures="on"
>        rebindinterval="1000"
>        usehttps="on"
>        queue.dequeuebatchsize="300"
>        action.resumeretrycount="-1"
>    )
> }
> ```
> We have 41 services with similar configuration which push logs to AWS managed Elasticsearch.
> We also tried to setup the latest version of rsyslog and observed the same behaviour.
> For temporary fixing - We set up rebindinterval parameter to 1000 - it has helped to resolve situation for almost 2 weeks but then it happened again.
>
> Any clue how to fix this issue?
>
>
>

**Comment by gartemiev** [comment]
@davidelang , 

there are no errors on Elasticsearch side. 
>what is the volume of logs being delivered? sockets remain in close_wait for a few minutes

We have many pipelines which are being pushed logs to Elasticsearch so it is difficult to determine. But this is not a heavy load. 
Connections to Elasticsearch remain in CLOSE_WAIT state constantly. We've started observing this behavior once We switched to Ubuntu 20.04.

**Comment by davidelang** [comment]
impstats will give you the information about log delivery rates.

'not a heavy load' is a relative term with nothing to judge it by. for some 
people this is a few thousand logs per second, for others, it's tens of logs per 
minute. :-)

**Comment by gartemiev** [comment]
@davidelang,

```
Sun Feb  7 08:51:33 2021: action-0-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-1-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-2-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-3-omelasticsearch: origin=core.action processed=48133 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-4-omelasticsearch: origin=core.action processed=274256 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-5-omelasticsearch: origin=core.action processed=102419 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-8-omelasticsearch: origin=core.action processed=2507419 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-9-omelasticsearch: origin=core.action processed=3 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-10-omelasticsearch: origin=core.action processed=204260 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-12-omelasticsearch: origin=core.action processed=1057 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-13-omelasticsearch: origin=core.action processed=158546 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-14-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-15-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-16-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-17-omelasticsearch: origin=core.action processed=1126 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-18-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-19-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-20-omelasticsearch: origin=core.action processed=178832 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-21-omelasticsearch: origin=core.action processed=257179 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-22-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-23-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-24-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-25-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-26-omelasticsearch: origin=core.action processed=24197 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-27-omelasticsearch: origin=core.action processed=305713 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-28-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-31-omelasticsearch: origin=core.action processed=356 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-32-omelasticsearch: origin=core.action processed=871800 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-33-omelasticsearch: origin=core.action processed=3025 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-34-omelasticsearch: origin=core.action processed=0 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-35-omelasticsearch: origin=core.action processed=1764 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-38-omelasticsearch: origin=core.action processed=11492753 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-39-omelasticsearch: origin=core.action processed=161150 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-44-omelasticsearch: origin=core.action processed=2066 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-45-omelasticsearch: origin=core.action processed=102238 failed=0 suspended=0 suspended.duration=0 resumed=0 
Sun Feb  7 08:51:33 2021: action-0-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-1-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-2-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-3-omelasticsearch queue: origin=core.queue size=0 enqueued=48133 full=0 discarded.full=0 discarded.nf=0 maxqsize=28 
Sun Feb  7 08:51:33 2021: action-4-omelasticsearch queue: origin=core.queue size=0 enqueued=274256 full=0 discarded.full=0 discarded.nf=0 maxqsize=18 
Sun Feb  7 08:51:33 2021: action-5-omelasticsearch queue: origin=core.queue size=0 enqueued=102419 full=0 discarded.full=0 discarded.nf=0 maxqsize=276 
Sun Feb  7 08:51:33 2021: action-8-omelasticsearch queue: origin=core.queue size=0 enqueued=2507419 full=0 discarded.full=0 discarded.nf=0 maxqsize=407 
Sun Feb  7 08:51:33 2021: action-9-omelasticsearch queue: origin=core.queue size=0 enqueued=3 full=0 discarded.full=0 discarded.nf=0 maxqsize=1 
Sun Feb  7 08:51:33 2021: action-10-omelasticsearch queue: origin=core.queue size=0 enqueued=204260 full=0 discarded.full=0 discarded.nf=0 maxqsize=659 
Sun Feb  7 08:51:33 2021: action-12-omelasticsearch queue: origin=core.queue size=0 enqueued=1057 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Sun Feb  7 08:51:33 2021: action-13-omelasticsearch queue: origin=core.queue size=0 enqueued=158546 full=0 discarded.full=0 discarded.nf=0 maxqsize=15 
Sun Feb  7 08:51:33 2021: action-14-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-15-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-16-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-17-omelasticsearch queue: origin=core.queue size=0 enqueued=1126 full=0 discarded.full=0 discarded.nf=0 maxqsize=1 
Sun Feb  7 08:51:33 2021: action-18-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-19-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-20-omelasticsearch queue: origin=core.queue size=0 enqueued=178832 full=0 discarded.full=0 discarded.nf=0 maxqsize=47 
Sun Feb  7 08:51:33 2021: action-21-omelasticsearch queue: origin=core.queue size=0 enqueued=257179 full=0 discarded.full=0 discarded.nf=0 maxqsize=47 
Sun Feb  7 08:51:33 2021: action-22-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-23-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-24-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-25-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-26-omelasticsearch queue: origin=core.queue size=0 enqueued=24197 full=0 discarded.full=0 discarded.nf=0 maxqsize=31 
Sun Feb  7 08:51:33 2021: action-27-omelasticsearch queue: origin=core.queue size=0 enqueued=305713 full=0 discarded.full=0 discarded.nf=0 maxqsize=353 
Sun Feb  7 08:51:33 2021: action-28-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-31-omelasticsearch queue: origin=core.queue size=0 enqueued=356 full=0 discarded.full=0 discarded.nf=0 maxqsize=3 
Sun Feb  7 08:51:33 2021: action-32-omelasticsearch queue: origin=core.queue size=0 enqueued=871800 full=0 discarded.full=0 discarded.nf=0 maxqsize=322 
Sun Feb  7 08:51:33 2021: action-33-omelasticsearch queue: origin=core.queue size=0 enqueued=3025 full=0 discarded.full=0 discarded.nf=0 maxqsize=200 
Sun Feb  7 08:51:33 2021: action-34-omelasticsearch queue: origin=core.queue size=0 enqueued=0 full=0 discarded.full=0 discarded.nf=0 maxqsize=0 
Sun Feb  7 08:51:33 2021: action-35-omelasticsearch queue: origin=core.queue size=0 enqueued=1764 full=0 discarded.full=0 discarded.nf=0 maxqsize=346 
Sun Feb  7 08:51:33 2021: action-38-omelasticsearch queue: origin=core.queue size=0 enqueued=11492753 full=0 discarded.full=0 discarded.nf=0 maxqsize=639 
Sun Feb  7 08:51:33 2021: action-39-omelasticsearch queue: origin=core.queue size=0 enqueued=161150 full=0 discarded.full=0 discarded.nf=0 maxqsize=17 
Sun Feb  7 08:51:33 2021: action-44-omelasticsearch queue: origin=core.queue size=0 enqueued=2066 full=0 discarded.full=0 discarded.nf=0 maxqsize=2 
Sun Feb  7 08:51:33 2021: action-45-omelasticsearch queue: origin=core.queue size=0 enqueued=102238 full=0 discarded.full=0 discarded.nf=0 maxqsize=266 
```

**Comment by davidelang** [comment]
this is under load?

please post your full config. This seems to indicate that you have 45 different 
omelasticsearch actions. since a HUP will close and reopen connections, this 
will result in a lot of close_wait sockets after a HUP.

David Lang

**Comment by gartemiev** [comment]
@davidelang ,

I've provided you with full configuration and output which you asked regarding pushing logs to Elasticsearch. 

>is seems to indicate that you have 45 different omelasticsearch actions

that's correct 45.  

> since a HUP will close and reopen connections, this will result in a lot of close_wait sockets after a HUP.

How to prevent this? On Ubuntu 18.04 where was a bit older version of rsyslog - all was working fine.

**Comment by gartemiev** [comment]
@davidelang , so how can I fix this problem?

**Comment by davidelang** [comment]
when you say 'a lot of' close_wait sockets, how many? 50, 100, 1000?
what is the problem they are causing?

one way to reduce the number is to have fewer actions that use omelasticsearch, 
are there different parameters for each of the 40+ calls? or could you combine 
them by having a ruleset that has the omelasticsearch action in it that is 
called from different places in your ruleset?

you can change the timeout for close_wait at the os level, but that needs to be 
done carefully, close_wait exists for a reason (it's timeout can probably be 
lowered a bit from the default, even round-the-world latency is less than what 
was common when dial-up connections were common)

It's not clear that this is anything other than 'working as designed' at this 
point (but I could be wrong, which is why I ask the couple of questions at the 
beginning)

David Lang

**Comment by gartemiev** [comment]
@davidelang 

when it reaches 11-18 CLOSE_WAIT connections - it causes significant CPU load and increasing the size of main_queue. 

>are there different parameters for each of the 40+ calls?

parameters are the same the only thing which differs is index name and port number. 

But if I push everything into single pipeline what will be a sense in it? Pipelines are designed to separate different kinds of logs or I am missing something here?

**Comment by davidelang** [comment]
On Sun, 7 Feb 2021, George Artemiev wrote:

> @davidelang
>
> when it reaches 11-18 CLOSE_WAIT connections - it causes significant CPU load and increasing the size of main_queue.

that is odd, close_wait connections should not cause slowdowns, can you get a 
couple pstats reports from a time when this is happening? I think what we have 
here is correlation, not causation.

an increasing size of the main queue indicates a problem in delivering messages.

there could be something else going on with the config, but without the full 
config, it's impossible to know.

>> are there different parameters for each of the 40+ calls?
>
> parameters are the same the only thing which differs is index name and port number.

port number is not a parameter that can be a variable

> But if I push everything into single pipeline what will be a sense in it? Pipelines are designed to separate different kinds of logs or I am missing something here?

unless you are talking about a pipeline on the elasticsearch side, I suspect 
that you are minunderstanding how things are working inside rsyslog, but we 
would need to full config to talk about that. If everything is using the main 
queue, then it's not different 'pipelines'

On the elasticsearch side, I'm not sure that having a different port for every 
index is really going to be any better than having everything go through one 
listener to all the different indexes (that's the normal mode of operation for 
ES, and it's pretty good at it)

David Lang

**Comment by gartemiev** [comment]
@davidelang 

>an increasing size of the main queue indicates a problem in delivering messages.

yes but it happens in a week when amount of CLOSE_WAIT reaches 10 or more. 

> but we would need to full config to talk about that.


**cat /etc/rsyslog.d/20-ufw.conf** 
```
# Log kernel generated UFW log messages to file
:msg,contains,"[UFW " /var/log/ufw.log

# Uncomment the following to stop logging anything that matches the last rule.
# Doing this will stop logging kernel generated UFW log messages to the file
# normally containing kern.* messages (eg, /var/log/kern.log)
#& stop
```

**cat /etc/rsyslog.d/21-cloudinit.conf** 
```
# Log cloudinit generated log messages to file
:syslogtag, isequal, "[CLOUDINIT]" /var/log/cloud-init.log

# comment out the following line to allow CLOUDINIT messages through.
# Doing so means you'll also get CLOUDINIT messages in /var/log/syslog
& stop
```


**cat /etc/rsyslog.d/30-forward.conf**
``` 
### THIS FILE IS MANAGED BY PUPPET. ANY MANUAL CHANGES WILL GET OVERWRITTEN.

input(type="imfile" File="/var/log/syslog" Tag="syslog" Severity="info" Facility="local3")
input(type="imfile" File="/var/log/rsyslog-stats.log" Tag="rsyslog-stats" Severity="info" Facility="local3")
```


**cat /etc/rsyslog.d/35-remote.conf** 
```
### THIS FILE IS MANAGED BY PUPPET. ANY MANUAL CHANGES WILL GET OVERWRITTEN.

$ActionQueueType LinkedList # use asynchronous processing
$ActionQueueFileName impstats-spool1 # set file name, also enables disk mode
$ActionResumeRetryCount -1 # infinite retries on insert failure
$ActionQueueSaveOnShutdown on # save in-memory data if rsyslog shuts down
local3.* @@sinkrr.xxxx
```

```
cat /etc/rsyslog.d/40-stop.conf 
### THIS FILE IS MANAGED BY PUPPET. ANY MANUAL CHANGES WILL GET OVERWRITTEN.

if prifilt("local3.*") then {
    stop
}
```
**cat /etc/rsyslog.d/50-default.conf**
```
#  Default rules for rsyslog.
#
#			For more information see rsyslog.conf(5) and /etc/rsyslog.conf

#
# First some standard log files.  Log by facility.
#
auth,authpriv.*			/var/log/auth.log
*.*;auth,authpriv.none		-/var/log/syslog
#cron.*				/var/log/cron.log
#daemon.*			-/var/log/daemon.log
kern.*				-/var/log/kern.log
#lpr.*				-/var/log/lpr.log
mail.*				-/var/log/mail.log
#user.*				-/var/log/user.log

#
# Logging for the mail system.  Split it up so that
# it is easy to write scripts to parse these files.
#
#mail.info			-/var/log/mail.info
#mail.warn			-/var/log/mail.warn
mail.err			/var/log/mail.err

#
# Some "catch-all" log files.
#
#*.=debug;\
#	auth,authpriv.none;\
#	news.none;mail.none	-/var/log/debug
#*.=info;*.=notice;*.=warn;\
#	auth,authpriv.none;\
#	cron,daemon.none;\
#	mail,news.none		-/var/log/messages

#
# Emergencies are sent to everybody logged in.
#
*.emerg				:omusrmsg:*

#
# I like to have messages displayed on the console, but only on a virtual
# console I usually leave idle.
#
#daemon,mail.*;\
#	news.=crit;news.=err;news.=notice;\
#	*.=debug;*.=info;\
#	*.=notice;*.=warn	/dev/tty8
```

**cat /etc/rsyslog.conf**
```
module(load="imuxsock") # provides support for local system logging
$MaxMessageSize 74k
module(load="omkafka")
module(load="impstats" interval="300" severity="7" log.syslog="off" log.file="/var/log/rsyslog-stats.log")
module(load="omelasticsearch")
module(load="imfile")
module(load="omrelp")

# provides UDP syslog reception
module(load="imudp")

# provides TCP syslog reception
module(load="imtcp" maxlisteners="50")

# provides kernel logging support and enable non-kernel klog messages
module(load="imklog" permitnonkernelfacility="on")

###########################
#### GLOBAL DIRECTIVES ####
###########################

#
# Use traditional timestamp format.
# To enable high precision timestamps, comment out the following line.
#
#$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# Filter duplicated messages
$RepeatedMsgReduction on

#
# Set the default permissions for all log files.
#
$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

#
# Where to place spool and state files
#
$WorkDirectory /var/spool/rsyslog

#
# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/puppet/*.conf
#
$IncludeConfig /etc/rsyslog.d/*.conf
```

I don't see a sense to provide with 45 identical configurations for omelasticsearch pipelines which I did above for single pipeline.

>unless you are talking about a pipeline on the elasticsearch side

If We setup single pipeline for omelasticsearch - then everything will go through that port and it will be difficult to debug issues. Having separate pipelines like now allow easier debug of errors.

**Comment by gartemiev** [comment]
@davidelang ,

once I disabled **rebindinterval** like you said - in 15 minutes I am starting seeing increasing of CLOSE_WAIT connections: 
```
(production) root@dev-sink-1:~$ netstat -anp |grep rsys |grep 443 |grep -c CL
12
(production) root@dev-sink-1:~$ netstat -anp |grep rsys |grep 443 |grep -c CL
18
```
This amount of CLOSE_WAIT connections is not being decreased at all it remains forever.

I still don't see any errors in Elasticsearch at all. I also do not see any errors in rsyslog.

**Comment by gartemiev** [comment]
@rgerhards , can you please help with this?

**Comment by gartemiev** [comment]
After consolidating it to single Elasticsearch output - CLOSE_WAIT have disappeared. Rsyslog doesn't support multiple Elasticsearch outputs on the same machine since it will cause CLOSE_WAIT connections which will add additional load to it. 

@davidelang , thanks for the support and pointing to correct direction regarding this issue.

**Comment by rgerhards** [comment]
> After consolidating it to single Elasticsearch output - CLOSE_WAIT have disappeared. Rsyslog doesn't support multiple Elasticsearch outputs on the same machine since it will cause CLOSE_WAIT connections which will add additional load to it.

being late to the tracker, but just for the record: I don't see why multiple Elasticsearch outputs could call this issue. Maybe it's a problem with (a specific version of) libcurl?
