### ISSUE TITLE
Rsyslog variable filename not matching to actual input filename but Rsyslog forwarding to syslog server

### ISSUE THREAD

**Issue by vissueswar** [rsyslog/rsyslog#4747]
### Configuration files code : For multiple file names 
$InputFileName /var/log/NIMI/*_NIMI_EQT.ini_EventsLog.txt
$InputFileTag NIMI
$InputFileStateFile Stat-NIMI
$InputRunFileMonitor

Inputs files : 
Filename1 : 02-Dec-2021_NIMI.ini_EventsLog.txt
Filename2 : 03-Dec-2021_NIMI.ini_EventsLog.txt

Problem : 
There is no "_EQT" in the actual file name but log messages are forwarding to syslog server by reading from files *NIMI.ini_EventsLog.txt. I am not getting the logic, how it is reading the files with different name.

**Comment by rgerhards** [comment]
Is this the only file monitor configured? Which rsyslog version?

**Comment by vissueswar** [comment]
Environment
- rsyslog version: 8.24.0-57.el7_9.1
- platform: RHEL 7.9

Input log file monitored is generated daily based on date DD-MMM-YYYY_NIMI.ini_EventsLog.txt for example : 03-Dec-2021_NIMI.ini_EventsLog.txt

**Comment by davidelang** [comment]
8.24 was released almost 5 years ago, redhat has backported some fixes to the 
version they ship, but the community doesn't track what they've backported and 
can't support it as it's missing so much that's happened during that time. 
Please install a current (8.21xx) version that the community can support to see 
if we've fixed the problem in this time.

David Lang

**Comment by rgerhards** [comment]
Well, I still see the most important question on number of file monitors (actually full config TBH) unanswered. But upgrading is definitely a good idea.

**Comment by rgerhards** [comment]
Apologies for the very late reply. This is probably no longer relevant to the original reporter, but I am adding the conclusion for people who arrive here via search while we work through the backlog. We do not close rsyslog issues lightly, and we are not closing this merely because of age.

Triage result: not reproducible / needs reporter info.

Reasoning: Old RHEL 7 / rsyslog 8.24.0 config-incomplete support report; requested full monitor config/current repro was not supplied.

If this still reproduces on a current rsyslog release and maintained platform, please open a new issue with the current version, complete configuration, logs, and a minimal reproducer so we can investigate it as a fresh current problem.
