### ISSUE TITLE
Non-existing CA file cause memory usage increase

### ISSUE THREAD

**Issue by pengyi37** [rsyslog/rsyslog#5135]
Hi, I found when configuring a non-existing CAfile path, the memory usage of  rsyslog kept increasing. This problem didn't happen in a high-level of rsyslog(8.2110, etc.). I compared the code of gltsglblInit() and found the difference:
![difference](https://github.com/rsyslog/rsyslog/assets/116337992/b7fad180-3145-46d3-8c76-f92d248ac77a)
I suspect there exists memory leak when the gnutls function gnutls_certificate_set_x509_trust_file failed. 

### Environment
- rsyslog version: 8.2006

### Rsyslog error:
```
error reading certificate file 'file_non_exist_cert.crt' - a common cause is that the file does not exist [v8.2006.0 try https://www.rsyslog.com/e/2078 ]
```

**Comment by rgerhards** [comment]
so you are saying you do not experience it in the current version of rsyslog? That would obviously mean the issue is fixed and there is an easy way forward.

**Comment by alorbach** [comment]
That code was moved here 2 years ago: 
https://github.com/rsyslog/rsyslog/blob/a71589b50735c6f6776cb9ab5bbead6ac7594b9f/runtime/nsd_gtls.c#L707

And infact the **gnutls_certificate_allocate_credentials** call allocates memory in pThis->xcred and I don't see it being freed on failure. A call for **gnutls_certificate_free_credentials** needs to be added.

I will take care on this issue.

**Comment by century6** [comment]
> 

Made any headway? :)

**Comment by century6** [comment]
> 

Made any headway? :)

**Comment by pengyi37** [comment]
@alorbach Hi, I tried the PR,  it seems there still exists some memory leak in the process of Connect() in nsd_gtls.c. Compared with the previous version, the issue of memory leak improved, but it still exists. Maybe there are another memory leak in Connect()?
### Steps
1. run the repro.sh
```
#!/bin/bash
int=1
while(( $int<=500 ))
do
        logger "hello"
        let "int++"
done
```
2. `systemctl status rsyslog`

**Comment by century6** [comment]
@alorbach Perhaps there is also a memory leak here:
![image](https://github.com/rsyslog/rsyslog/assets/30516382/4fa4e837-46ee-493a-878e-6eeca68fa04c)

**Comment by alorbach** [comment]
> @alorbach Perhaps there is also a memory leak here: ![image](https://user-images.githubusercontent.com/30516382/240891521-a0c34dfb-6463-49d8-ac76-e7c8ccffa152.png)

Good catch yes, amended by fix

**Comment by linzhuorong** [comment]
In the code, rsyslog 8.2110 also has this problem.
